-- 查看salaries表的完整结构
DESCRIBE salaries;

-- 或者查看所有字段名
SELECT COLUMN_NAME, DATA_TYPE, COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'salaries'
AND TABLE_SCHEMA = DATABASE()
ORDER BY ORDINAL_POSITION;

