CREATE TABLE IF NOT EXISTS `employee_form_update_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_set_id` BIGINT UNSIGNED NOT NULL,
  `employee_id` BIGINT UNSIGNED NOT NULL,
  `form_type` VARCHAR(30) NOT NULL COMMENT 'onboarding=员工入职登记表, registration=从业人员登记表',
  `original_data` TEXT NULL COMMENT '提交审批时的原数据快照',
  `new_data` TEXT NOT NULL COMMENT '待审批的新数据',
  `reason` VARCHAR(500) NULL COMMENT '修改原因',
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT 'pending=审批中, approved=已通过, rejected=已驳回',
  `approval_instance_id` BIGINT UNSIGNED NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `approved_at` DATETIME NULL,
  `rejected_at` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_employee_form_update_pending` (`employee_id`, `form_type`, `status`),
  INDEX `idx_employee_form_update_account_set` (`account_set_id`),
  INDEX `idx_employee_form_update_approval` (`approval_instance_id`),
  CONSTRAINT `fk_employee_form_update_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_employee_form_update_account_set` FOREIGN KEY (`account_set_id`) REFERENCES `account_sets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_employee_form_update_approval` FOREIGN KEY (`approval_instance_id`) REFERENCES `approval_instances` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_employee_form_update_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
